### ISSUE TITLE
Pretrained model vposer_grab.pt?

### ISSUE THREAD

**Issue by siddharthKatageri** [purvaten/FLEX#2]
Hi @purvaten 
By referring to the readme, I was able to download all the data and checkpoints except for ```vposer_grab.pt```.

The ```flex.yaml``` says 
```best_mnet_grab: 'flex/pretrained_models/ckpts/vposer_grab.pt'  # Pre-trained HAND-GRASPING (trained on GRAB right-hand)``` .
So I checked for it in GRAB website, but they only provide coarsenet.pt and refinenet.pt.

Where do I download ```vposer_grab.pt``` from??

Thanks!!

**Comment by siddharthKatageri** [comment]
I looked into the code, and in [here](https://github.com/purvaten/FLEX/blob/3c0941b8802ecc4bfe88e6480ed1da48ccca8c3d/flex/pretrained_models/loader_vposer.py#L27), the VPoser model pre-trained on AMASS is loaded, as ```cfg.vposer_dset='amass'```. So it's fine if there is no ```vposer_grab.pt```.

But I had a doubt, please help me think through it,
I went through the paper, and found that you use VPoser (for prior over full-body poses) and GrabNet (for prior over right hand grasps). If VPoser is for full-body prior, is using VPoser model pre-trained on GRAB (right hand) correct? Won't it fail to provide prior of full-body pose if that's the case?

**Comment by purvaten** [comment]
Hi @siddharthKatageri, good catch! `vposer_grab.pt` is indeed unnecessary and not used by the code. It was something I had created at some point -- it was a checkpoint of the VPoser model architecture but pre-trained on full-body data from GRAB only, not the rest of AMASS. Because GRAB-only poses are not as diverse as the rest of AMASS, it doesn't work great in practice.

I will remove it from the requirements.
